let countdown=10;
setTimeout(function(){
    document.getElementById("mms").innerHTML=countdown--;
    setTimeout(function(){
        document.getElementById("mms").innerHTML=countdown--;
        setTimeout(function(){
            document.getElementById("mms").innerHTML=countdown--;
            setTimeout(function(){
                document.getElementById("mms").innerHTML=countdown--;
                setTimeout(function(){
                    document.getElementById("mms").innerHTML=countdown--;
                    setTimeout(function(){
                        document.getElementById("mms").innerHTML=countdown--;
                        setTimeout(function(){
                            document.getElementById("mms").innerHTML=countdown--;
                            setTimeout(function(){
                                document.getElementById("mms").innerHTML=countdown--;
                                setTimeout(function(){
                                    document.getElementById("mms").innerHTML=countdown--;
                                    setTimeout(function(){
                                        document.getElementById("mms").innerHTML=countdown--;
                                        setTimeout(function(){
                                            document.getElementById("mms").innerHTML="HAPPY INDEPENDENCE DAY 2021";
                                            },1000)
                                        },1000)
                                    },1000)
                                },1000)
                            },1000)
                        },1000)
                    },1000)
                },1000)
            },1000)
        },1000)
    },1000)
